// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmenTestAPI.Data;

#nullable disable

namespace OmenTestAPI.Migrations
{
    [DbContext(typeof(OmenContext))]
    [Migration("20211217192431_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("OmenModels.ShipModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Damage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIllegal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissileSpeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerRequirement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sensor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shield")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotSpacesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Speed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stealth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Volley")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ShipModules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6df60c58-d182-4a3b-88b1-6453d12648f2"),
                            Armor = 0,
                            Category = 7,
                            Damage = 0,
                            DamageType = 0,
                            Description = "A section of the ship's hull that is meant to have a module installed.",
                            IsIllegal = false,
                            MissileSpeed = 0,
                            Name = "Empty Module Slot",
                            PowerRequirement = 0,
                            Range = 0,
                            Sensor = 0,
                            Shield = 0,
                            SlotSpacesRequired = 0,
                            Speed = 0,
                            Stealth = 0,
                            Value = 0,
                            Volley = 0
                        });
                });

            modelBuilder.Entity("OmenModels.Starship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HullId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StarshipClassId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HullId");

                    b.HasIndex("StarshipClassId");

                    b.ToTable("Starships");
                });

            modelBuilder.Entity("OmenModels.StarshipClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseStealth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Slots")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StarshipClasses");
                });

            modelBuilder.Entity("OmenModels.StarshipHull", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Hitpoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialAbility")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StarshipHulls");
                });

            modelBuilder.Entity("ShipModuleStarship", b =>
                {
                    b.Property<Guid>("ModulesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StarshipsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ModulesId", "StarshipsId");

                    b.HasIndex("StarshipsId");

                    b.ToTable("ShipModuleStarship");
                });

            modelBuilder.Entity("OmenModels.Starship", b =>
                {
                    b.HasOne("OmenModels.StarshipHull", "Hull")
                        .WithMany()
                        .HasForeignKey("HullId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmenModels.StarshipClass", "StarshipClass")
                        .WithMany()
                        .HasForeignKey("StarshipClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hull");

                    b.Navigation("StarshipClass");
                });

            modelBuilder.Entity("ShipModuleStarship", b =>
                {
                    b.HasOne("OmenModels.ShipModule", null)
                        .WithMany()
                        .HasForeignKey("ModulesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmenModels.Starship", null)
                        .WithMany()
                        .HasForeignKey("StarshipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
